### PR TITLE
Option to use single quotes

### LINKED ISSUE #81: String quotes get changed from ' to " - should be the other way around
I'm using the autosave option in sublime and all ' quotes get changed to ". This leads to scss-lint errors. Is there a way to change the behavior?

### PR DESCRIPTION
**Pull request by mintuhouse**
based on [sass guidelines](https://github.com/HugoGiraudel/sass-guidelines/pull/27)
Fixes #81

### CODE REVIEW

**Comment by jeanpierreb** [comment]
Really looking forward to this getting merged

**Comment by badsyntax** [comment]
Hey @mintuhouse 

Thanks for this PR! Any chance you can add this setting option description to the README in the "Settings overview" section?

**Comment by mintuhouse** [comment]
@badsyntax: Added to readme

**Comment by badsyntax** [comment]
Thanks!

**Pull request merged**
